# Generated by Django 4.2.6 on 2023-10-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carona_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='horario',
            field=models.DateTimeField(verbose_name='Horário'),
        ),
    ]
