# Generated by Django 4.2.6 on 2023-10-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_carona_descricao_alter_carona_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caronas', to='main.veiculo', verbose_name='Veículo'),
        ),
    ]
